"""add conversations conversation_messages conversation_summaries

Revision ID: 038ab1fd9129
Revises: 0f245f269b1d
Create Date: 2026-09-01 15:43:55.761418

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '038ab1fd9129'
down_revision: str | None = '0f245f269b1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-moved ahead of `conversations`: a composite foreign key requires
    # its referenced columns to already carry a unique constraint at the
    # time the referencing table is created, not merely by the time the
    # migration finishes.
    op.create_unique_constraint('uq_receptionists_tenant_id_id', 'receptionists', ['tenant_id', 'id'])
    op.create_table('conversations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('receptionist_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('test', 'future_live', name='conversation_mode'), nullable=False),
    sa.Column('channel', sa.Enum('dashboard_test', name='conversation_channel'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', 'failed', name='conversation_status'), nullable=False),
    sa.Column('visitor_reference', sa.String(length=200), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('collected_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qualification_complete', sa.Boolean(), nullable=False),
    sa.Column('safety_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'receptionist_id'], ['receptionists.tenant_id', 'receptionists.id'], name='fk_conversations_tenant_receptionist', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_receptionist_id'), 'conversations', ['receptionist_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='conversation_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_tenant_id'), 'conversation_messages', ['tenant_id'], unique=False)
    op.create_index('uq_conversation_messages_idempotency_key', 'conversation_messages', ['conversation_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('uq_conversation_messages_sequence', 'conversation_messages', ['conversation_id', 'sequence_number'], unique=True)
    op.create_table('conversation_summaries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('captured_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_next_action', sa.String(length=100), nullable=True),
    sa.Column('generated_by_provider', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversation_summaries_tenant_id'), 'conversation_summaries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_summaries_tenant_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index('uq_conversation_messages_sequence', table_name='conversation_messages')
    op.drop_index('uq_conversation_messages_idempotency_key', table_name='conversation_messages', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index(op.f('ix_conversation_messages_tenant_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_receptionist_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###

    # Hand-moved after `conversations` is dropped: you cannot drop a unique
    # constraint while a composite foreign key still references it.
    op.drop_constraint('uq_receptionists_tenant_id_id', 'receptionists', type_='unique')

    # Dropping a table does not drop the Postgres ENUM type it used — without
    # this, a downgrade followed by another upgrade fails with "type already
    # exists" (same pattern established in 0f245f269b1d). Must run only after
    # every table using each type is already dropped, which is why these are
    # last.
    sa.Enum(name="conversation_message_role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="conversation_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="conversation_channel").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="conversation_mode").drop(op.get_bind(), checkfirst=True)
