"""add industry templates onboarding receptionist locations services faqs knowledge

Revision ID: 0f245f269b1d
Revises: 6c6136895656
Create Date: 2026-09-01 12:23:33.095110

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f245f269b1d'
down_revision: str | None = '6c6136895656'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_templates',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('default_terminology', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_welcome_message', sa.String(length=1000), nullable=False),
    sa.Column('default_suggested_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_qualification_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_safety_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_workflow', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version', name='uq_industry_templates_key_version')
    )
    op.create_index(op.f('ix_industry_templates_key'), 'industry_templates', ['key'], unique=False)
    op.create_table('business_locations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address_line', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('public_phone', sa.String(length=20), nullable=True),
    sa.Column('working_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_locations_tenant_id'), 'business_locations', ['tenant_id'], unique=False)
    op.create_index('uq_business_locations_one_primary_per_tenant', 'business_locations', ['tenant_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('business_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('short_description', sa.String(length=1000), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('public_email', sa.String(length=320), nullable=True),
    sa.Column('public_phone', sa.String(length=20), nullable=True),
    sa.Column('industry_template_id', sa.UUID(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_language', sa.String(length=8), nullable=False),
    sa.Column('supported_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('onboarding_status', sa.Enum('not_started', 'in_progress', 'completed', name='onboarding_status'), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_template_id'], ['industry_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('faqs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=5000), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_tenant_id'), 'faqs', ['tenant_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('manual', 'website', 'file_upload', name='knowledge_source_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='content_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_tenant_id'), 'knowledge_sources', ['tenant_id'], unique=False)
    op.create_table('receptionists',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('industry_template_id', sa.UUID(), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('welcome_message', sa.String(length=1000), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('default_language', sa.String(length=8), nullable=False),
    sa.Column('supported_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('suggested_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', name='receptionist_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['industry_template_id'], ['industry_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receptionists_tenant_id'), 'receptionists', ['tenant_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='content_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_source_id'), 'knowledge_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_tenant_id'), 'knowledge_documents', ['tenant_id'], unique=False)
    op.create_table('receptionist_workflows',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('receptionist_id', sa.UUID(), nullable=False),
    sa.Column('qualification_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qualification_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receptionist_id'], ['receptionists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receptionist_id')
    )
    op.create_index(op.f('ix_receptionist_workflows_tenant_id'), 'receptionist_workflows', ['tenant_id'], unique=False)
    op.create_table('services',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('price_note', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['business_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_tenant_id'), 'services', ['tenant_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_tenant_id'), 'knowledge_chunks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_tenant_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_services_tenant_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_receptionist_workflows_tenant_id'), table_name='receptionist_workflows')
    op.drop_table('receptionist_workflows')
    op.drop_index(op.f('ix_knowledge_documents_tenant_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_source_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_receptionists_tenant_id'), table_name='receptionists')
    op.drop_table('receptionists')
    op.drop_index(op.f('ix_knowledge_sources_tenant_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_faqs_tenant_id'), table_name='faqs')
    op.drop_table('faqs')
    op.drop_table('business_profiles')
    op.drop_index('uq_business_locations_one_primary_per_tenant', table_name='business_locations', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_business_locations_tenant_id'), table_name='business_locations')
    op.drop_table('business_locations')
    op.drop_index(op.f('ix_industry_templates_key'), table_name='industry_templates')
    op.drop_table('industry_templates')
    # ### end Alembic commands ###

    # Hand-added: dropping a table does NOT drop the native Postgres ENUM
    # type it used — without this, downgrade() followed by upgrade() again
    # would fail with "type ... already exists". Must run after every table
    # that uses these types has already been dropped above.
    sa.Enum(name="content_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="knowledge_source_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="receptionist_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="onboarding_status").drop(op.get_bind(), checkfirst=True)
