"""add widget installations visitor sessions contacts enquiries appointment requests handoffs

Revision ID: 1aa533d3cabf
Revises: 038ab1fd9129
Create Date: 2026-09-02 08:14:10.544700

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aa533d3cabf'
down_revision: str | None = '038ab1fd9129'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-added: the ConversationMode/ConversationChannel Python enums
    # (app/models/enums.py) gained a `widget` member in Phase 5, but
    # Alembic's autogenerate does not detect native Postgres enum VALUE
    # additions on an existing type — only whole-table/column diffs — so
    # this must be added explicitly. Must run outside the "add new value,
    # use it in the same transaction" restriction some Postgres versions
    # enforce; this migration's own upgrade() never inserts a 'widget' row
    # itself; see docs for the version note.
    op.execute("ALTER TYPE conversation_mode ADD VALUE IF NOT EXISTS 'widget'")
    op.execute("ALTER TYPE conversation_channel ADD VALUE IF NOT EXISTS 'widget'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_installations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('receptionist_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'revoked', name='widget_installation_status'), nullable=False),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('theme', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('launcher_position', sa.String(length=20), nullable=False),
    sa.Column('privacy_notice', sa.String(length=4000), nullable=False),
    sa.Column('ai_disclosure', sa.String(length=1000), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'receptionist_id'], ['receptionists.tenant_id', 'receptionists.id'], name='fk_widget_installations_tenant_receptionist', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_widget_installations_tenant_id'), 'widget_installations', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('normalized_email', sa.String(length=320), nullable=True),
    sa.Column('normalized_phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_contact_method', sa.Enum('email', 'phone', 'either', name='preferred_contact_method'), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_normalized_email'), 'contacts', ['normalized_email'], unique=False)
    op.create_index(op.f('ix_contacts_normalized_phone'), 'contacts', ['normalized_phone'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('widget_visitor_sessions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('widget_installation_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_installation_id'], ['widget_installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_widget_visitor_sessions_tenant_id'), 'widget_visitor_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_widget_visitor_sessions_widget_installation_id'), 'widget_visitor_sessions', ['widget_installation_id'], unique=False)
    op.create_table('appointment_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('receptionist_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('requested_time', sa.Time(), nullable=True),
    sa.Column('requested_time_window', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'declined', 'cancelled', name='appointment_request_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['business_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'receptionist_id'], ['receptionists.tenant_id', 'receptionists.id'], name='fk_appointment_requests_tenant_receptionist', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_requests_conversation_id'), 'appointment_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_appointment_requests_tenant_id'), 'appointment_requests', ['tenant_id'], unique=False)
    op.create_table('enquiries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('receptionist_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('new', 'qualified', 'closed', name='enquiry_status'), nullable=False),
    sa.Column('qualification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('qualification_complete', sa.Boolean(), nullable=False),
    sa.Column('recommended_next_action', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'receptionist_id'], ['receptionists.tenant_id', 'receptionists.id'], name='fk_enquiries_tenant_receptionist', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_enquiries_tenant_id'), 'enquiries', ['tenant_id'], unique=False)
    op.create_table('human_handoffs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('receptionist_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('preferred_contact_method', sa.Enum('email', 'phone', 'either', name='preferred_contact_method'), nullable=True),
    sa.Column('status', sa.Enum('open', 'claimed', 'resolved', 'cancelled', name='handoff_status'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'receptionist_id'], ['receptionists.tenant_id', 'receptionists.id'], name='fk_human_handoffs_tenant_receptionist', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_handoffs_conversation_id'), 'human_handoffs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_human_handoffs_tenant_id'), 'human_handoffs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_handoffs_tenant_id'), table_name='human_handoffs')
    op.drop_index(op.f('ix_human_handoffs_conversation_id'), table_name='human_handoffs')
    op.drop_table('human_handoffs')
    op.drop_index(op.f('ix_enquiries_tenant_id'), table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_index(op.f('ix_appointment_requests_tenant_id'), table_name='appointment_requests')
    op.drop_index(op.f('ix_appointment_requests_conversation_id'), table_name='appointment_requests')
    op.drop_table('appointment_requests')
    op.drop_index(op.f('ix_widget_visitor_sessions_widget_installation_id'), table_name='widget_visitor_sessions')
    op.drop_index(op.f('ix_widget_visitor_sessions_tenant_id'), table_name='widget_visitor_sessions')
    op.drop_table('widget_visitor_sessions')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_normalized_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_normalized_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_widget_installations_tenant_id'), table_name='widget_installations')
    op.drop_table('widget_installations')
    # ### end Alembic commands ###

    # Hand-added: `op.drop_table` does not drop the native Postgres enum
    # types `sa.Enum(...)` implicitly created for these columns — left
    # unremoved, a subsequent `upgrade()` re-running `create_table` would
    # fail with "type already exists". Drop each exactly once, after every
    # table that references it is gone. `preferred_contact_method` is used
    # by both `contacts` and `human_handoffs`, so it's dropped only here,
    # after both tables are dropped above.
    for enum_name in (
        "handoff_status",
        "appointment_request_status",
        "enquiry_status",
        "preferred_contact_method",
        "widget_installation_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)

    # Deliberately NOT reverted here: Postgres has no `ALTER TYPE ... DROP
    # VALUE`. Removing the `widget` value added to conversation_mode/
    # conversation_channel in upgrade() would require rebuilding those
    # enum types (and rewriting every row of the pre-existing
    # `conversations` table), which is destructive for a value that is
    # otherwise harmless to leave defined. Downgrading past this revision
    # removes every Phase 5 table/enum above; it does not attempt to
    # fully restore the exact enum type definition Phase 4 shipped with.
