"""add phase 6 operations dashboard: notes, activity, versioning

Revision ID: 4782a62b4927
Revises: 1aa533d3cabf
Create Date: 2026-09-02 13:35:57.541723

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4782a62b4927"
down_revision: str | None = "1aa533d3cabf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_events",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activity_events_tenant_entity", "activity_events", ["tenant_id", "entity_type", "entity_id"], unique=False
    )
    op.create_index(op.f("ix_activity_events_tenant_id"), "activity_events", ["tenant_id"], unique=False)
    op.create_table(
        "internal_notes",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("enquiry_id", sa.UUID(), nullable=True),
        sa.Column("appointment_request_id", sa.UUID(), nullable=True),
        sa.Column("human_handoff_id", sa.UUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "num_nonnulls(conversation_id, contact_id, enquiry_id, appointment_request_id, human_handoff_id) = 1",
            name="ck_internal_notes_exactly_one_target",
        ),
        sa.ForeignKeyConstraint(["appointment_request_id"], ["appointment_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["author_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["enquiry_id"], ["enquiries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["human_handoff_id"], ["human_handoffs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_internal_notes_appointment_request_id"), "internal_notes", ["appointment_request_id"], unique=False
    )
    op.create_index(op.f("ix_internal_notes_contact_id"), "internal_notes", ["contact_id"], unique=False)
    op.create_index(op.f("ix_internal_notes_conversation_id"), "internal_notes", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_internal_notes_enquiry_id"), "internal_notes", ["enquiry_id"], unique=False)
    op.create_index(op.f("ix_internal_notes_human_handoff_id"), "internal_notes", ["human_handoff_id"], unique=False)
    op.create_index(op.f("ix_internal_notes_tenant_id"), "internal_notes", ["tenant_id"], unique=False)
    # server_default is required here (not just the Python-side model
    # default) because these columns are NOT NULL and every table already
    # has existing rows from Phases 1-5 — without it, ADD COLUMN would fail
    # against any non-empty table. Left in place afterward as a harmless
    # DB-level safety net; it never overrides an explicit application value.
    op.add_column("appointment_requests", sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
    op.add_column(
        "conversation_messages",
        sa.Column("is_fallback_response", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "conversations", sa.Column("had_safety_event", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "conversations", sa.Column("had_clinic_emergency", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column("enquiries", sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
    op.add_column("human_handoffs", sa.Column("assigned_user_id", sa.UUID(), nullable=True))
    op.add_column("human_handoffs", sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
    op.create_foreign_key(
        "fk_human_handoffs_assigned_user_id",
        "human_handoffs",
        "users",
        ["assigned_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "widget_visitor_sessions",
        sa.Column("is_platform_preview", sa.Boolean(), nullable=False, server_default=sa.false()),
    )

    # Enquiry pipeline refinement (Phase 6) — new values only, `closed`
    # (Phase 5) is kept unmigrated as a legacy synonym of `archived`; see
    # EnquiryStatus's docstring and docs/database-schema.md for why no
    # existing row is rewritten. Postgres requires each ADD VALUE to commit
    # before the value can be used — matching the exact pattern already
    # established in 1aa533d3cabf for conversation_mode/conversation_channel.
    op.execute("ALTER TYPE enquiry_status ADD VALUE IF NOT EXISTS 'contacted'")
    op.execute("ALTER TYPE enquiry_status ADD VALUE IF NOT EXISTS 'appointment_requested'")
    op.execute("ALTER TYPE enquiry_status ADD VALUE IF NOT EXISTS 'in_progress'")
    op.execute("ALTER TYPE enquiry_status ADD VALUE IF NOT EXISTS 'won'")
    op.execute("ALTER TYPE enquiry_status ADD VALUE IF NOT EXISTS 'lost'")
    op.execute("ALTER TYPE enquiry_status ADD VALUE IF NOT EXISTS 'archived'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("widget_visitor_sessions", "is_platform_preview")
    op.drop_constraint("fk_human_handoffs_assigned_user_id", "human_handoffs", type_="foreignkey")
    op.drop_column("human_handoffs", "version")
    op.drop_column("human_handoffs", "assigned_user_id")
    op.drop_column("enquiries", "version")
    op.drop_column("conversations", "had_clinic_emergency")
    op.drop_column("conversations", "had_safety_event")
    op.drop_column("conversation_messages", "is_fallback_response")
    op.drop_column("appointment_requests", "version")
    op.drop_index(op.f("ix_internal_notes_tenant_id"), table_name="internal_notes")
    op.drop_index(op.f("ix_internal_notes_human_handoff_id"), table_name="internal_notes")
    op.drop_index(op.f("ix_internal_notes_enquiry_id"), table_name="internal_notes")
    op.drop_index(op.f("ix_internal_notes_conversation_id"), table_name="internal_notes")
    op.drop_index(op.f("ix_internal_notes_contact_id"), table_name="internal_notes")
    op.drop_index(op.f("ix_internal_notes_appointment_request_id"), table_name="internal_notes")
    op.drop_table("internal_notes")
    op.drop_index(op.f("ix_activity_events_tenant_id"), table_name="activity_events")
    op.drop_index("ix_activity_events_tenant_entity", table_name="activity_events")
    op.drop_table("activity_events")
    # ### end Alembic commands ###

    # Deliberately NOT reverted: Postgres has no `ALTER TYPE ... DROP
    # VALUE`. Removing the six values added to enquiry_status in upgrade()
    # would require rebuilding that enum type and rewriting every row of
    # the pre-existing `enquiries` table — destructive, for values that are
    # otherwise harmless to leave defined. Matches the identical, already-
    # accepted precedent in 1aa533d3cabf for conversation_mode/
    # conversation_channel. Downgrading past this revision leaves
    # 'contacted', 'appointment_requested', 'in_progress', 'won', 'lost',
    # and 'archived' as valid (if unused by any older application code)
    # enquiry_status values.
