"""add phase 8 integrations

Revision ID: ee559f240268
Revises: 161846266d69
Create Date: 2026-09-03 13:33:35.815920

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ee559f240268"
down_revision: str | None = "161846266d69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-reviewed: generated via `alembic revision --autogenerate` against
    # app/models/integration.py, then checked column-by-column against that
    # module and had enum-type cleanup added to downgrade() below (autogenerate
    # never emits that — see the precedent in 1aa533d3cabf's downgrade()).
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_connections",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "connector_type",
            sa.Enum("mock", "webhook", "revenue_brain", "sales_employee", name="integration_connector_type"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("configured", "verified", "paused", "failing", "disabled", name="integration_connection_status"),
            nullable=False,
        ),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled_event_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signing_secret_ciphertext", sa.String(length=2000), nullable=True),
        sa.Column("signing_secret_key_version", sa.Integer(), nullable=True),
        sa.Column("inbound_api_key_hash", sa.String(length=64), nullable=True),
        sa.Column("inbound_api_key_prefix", sa.String(length=20), nullable=True),
        sa.Column("inbound_api_key_last_four", sa.String(length=4), nullable=True),
        sa.Column("inbound_api_key_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inbound_api_key_rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_delivery_status",
            sa.Enum("success", "retryable_failure", "permanent_failure", name="integration_last_delivery_status"),
            nullable=True,
        ),
        sa.Column("last_inbound_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_integration_connections_tenant_name"),
    )
    op.create_index(
        op.f("ix_integration_connections_inbound_api_key_hash"),
        "integration_connections",
        ["inbound_api_key_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_integration_connections_tenant_id"), "integration_connections", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_integration_connections_tenant_status", "integration_connections", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "inbound_integration_events",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("external_event_id", sa.String(length=300), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("processed", "rejected", name="inbound_integration_event_status"), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["integration_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "connection_id", "external_event_id", name="uq_inbound_integration_events_tenant_conn_ext"
        ),
    )
    op.create_index(
        op.f("ix_inbound_integration_events_tenant_id"), "inbound_integration_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "integration_outbox_events",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sa.String(length=300), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "claimed", "delivered", "dead_letter", name="integration_outbox_event_status"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.String(length=200), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["integration_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "connection_id", "dedup_key", name="uq_integration_outbox_events_tenant_conn_dedup"
        ),
    )
    op.create_index(
        "ix_integration_outbox_events_claim", "integration_outbox_events", ["status", "available_at"], unique=False
    )
    op.create_index(
        "ix_integration_outbox_events_connection",
        "integration_outbox_events",
        ["connection_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_outbox_events_tenant_id"), "integration_outbox_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "integration_delivery_attempts",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("outbox_event_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("success", "retryable_failure", "permanent_failure", name="integration_delivery_attempt_status"),
            nullable=False,
        ),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["integration_connections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["outbox_event_id"], ["integration_outbox_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_integration_delivery_attempts_outbox",
        "integration_delivery_attempts",
        ["outbox_event_id", "attempt_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_delivery_attempts_tenant_id"), "integration_delivery_attempts", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_integration_delivery_attempts_tenant_id"), table_name="integration_delivery_attempts")
    op.drop_index("ix_integration_delivery_attempts_outbox", table_name="integration_delivery_attempts")
    op.drop_table("integration_delivery_attempts")
    op.drop_index(op.f("ix_integration_outbox_events_tenant_id"), table_name="integration_outbox_events")
    op.drop_index("ix_integration_outbox_events_connection", table_name="integration_outbox_events")
    op.drop_index("ix_integration_outbox_events_claim", table_name="integration_outbox_events")
    op.drop_table("integration_outbox_events")
    op.drop_index(op.f("ix_inbound_integration_events_tenant_id"), table_name="inbound_integration_events")
    op.drop_table("inbound_integration_events")
    op.drop_index("ix_integration_connections_tenant_status", table_name="integration_connections")
    op.drop_index(op.f("ix_integration_connections_tenant_id"), table_name="integration_connections")
    op.drop_index(op.f("ix_integration_connections_inbound_api_key_hash"), table_name="integration_connections")
    op.drop_table("integration_connections")
    # ### end Alembic commands ###

    # Hand-added (see 1aa533d3cabf's downgrade() for the same pattern):
    # op.drop_table does not drop the native Postgres enum types created for
    # these columns. Drop each exactly once, after every table referencing it
    # is already gone above. `integration_delivery_attempt_status` and
    # `integration_last_delivery_status` share the same Python enum
    # (DeliveryAttemptStatus) but are deliberately separate Postgres types —
    # see app/models/integration.py — so both must be dropped independently.
    for enum_name in (
        "integration_delivery_attempt_status",
        "integration_outbox_event_status",
        "inbound_integration_event_status",
        "integration_last_delivery_status",
        "integration_connection_status",
        "integration_connector_type",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
