import type { Metadata } from "next";
import { IndustryPage, type IndustryPageContent } from "@/components/marketing/IndustryPage";
import { buildMetadata } from "@/lib/seo";

const content: IndustryPageContent = {
  slug: "clinics",
  name: "Clinics",
  headline: "A front desk that answers questions and captures appointment requests — around the clock.",
  subhead:
    "AI Receptionist handles general information and FAQs, collects appointment requests for staff to confirm, and hands off to a person when a conversation needs one. It does not diagnose, prescribe, or replace a medical professional.",
  painPoints: [
    "Phone lines are busy during clinic hours, so after-hours questions go unanswered.",
    "Front-desk staff spend time answering the same FAQs repeatedly.",
    "Appointment requests submitted online often lack the details staff need to confirm them.",
    "Urgent-sounding messages need a clear, consistent response — not an improvised one.",
  ],
  workflow: [
    { title: "Visitor asks a question", detail: "General information, hours, and service questions are answered from your own FAQs and knowledge base." },
    { title: "Service and location selection", detail: "If you offer more than one service or location, the assistant helps narrow down which one applies." },
    { title: "Contact and appointment capture", detail: "Structured appointment requests and contact details are collected for your team to confirm." },
    { title: "Handoff when needed", detail: "A visitor can ask for a person at any point, and emergency-language triggers a fixed safety response." },
  ],
  capabilities: [
    "Grounded answers to general information and FAQs from your own content",
    "Appointment requests — collected for staff confirmation, never presented as a guaranteed booking",
    "Service and location selection when you offer more than one",
    "Contact capture with consent tracked separately from contact details",
    "Human handoff on request, or automatically for emergency-language messages",
    "Deterministic, non-model safety rules for emergency language and out-of-scope medical requests",
  ],
  safety: [
    "This assistant does not diagnose, prescribe, or replace a medical professional.",
    "Emergency-language messages (e.g. chest pain, severe bleeding, suicidal language) trigger a fixed, deterministic response directing the visitor to call emergency services — this response is not generated by the AI model and cannot be talked around.",
    "Appointment requests are requests only, confirmed by clinic staff — never a guaranteed booking.",
  ],
  demoHref: "/demo/clinic",
  demoLabel: "Try the clinic demo",
  faq: [
    { question: "Can it diagnose a condition or recommend treatment?", answer: "No. It answers general information questions from your own content and directs anything requiring clinical judgment to your staff or emergency services." },
    { question: "What happens if someone describes a medical emergency?", answer: "A fixed, deterministic safety response runs before any AI-generated reply, directing the visitor to call emergency services immediately — this is not something the AI model decides." },
    { question: "Is an appointment request the same as a booking?", answer: "No — it's a request your staff reviews and confirms, and the assistant never tells a visitor their appointment is booked." },
  ],
};

export const metadata: Metadata = buildMetadata({
  title: "AI Receptionist for Clinics",
  description: "General information, appointment requests, and deterministic emergency-language safety handling for clinics.",
  path: "/industries/clinics",
});

export default function ClinicsIndustryPage() {
  return <IndustryPage content={content} />;
}
